apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::761016821565:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-7DS9lO7lQlwS
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::761016821565:role/UdacityFlaskDeployCBKubectlRole
      username: build  
kind: ConfigMap
metadata:
  creationTimestamp: "2023-12-10T15:27:24Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1366"
  uid: 36e3146b-ea92-490b-a86a-4c41147f255a
